version: "3"
services:
  nodejs:
    container_name: nodejs
    image: node:12
    volumes:
      - ./nextjs:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm ci && npm run dev"
    ports:
      - 3000:3000